version: 0.2

phases:
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started
        - ng build --prod
        - cp server.js ./dist
        - cp package.json ./dist
artifacts:
    files:
        - 'dist/*'
